### ISSUE TITLE
iex.chart() time range is not send

### ISSUE THREAD

**Issue by yutingli119** [iexcloud/iexjs#115]
**Describe the bug**
Copied and pasted this code from readme and change the time range from"1m" to 5m (or other valid time range value), the api still gives data for 1m.  It seems this way only the symbol is sent but not the time range.  
```
client.chart("AAPL", "5m").then((res) => {
    console.log(res);
});

```

**Comment by timkpaine** [comment]
As of at least 0.3.0 the options are passed in an object https://github.com/iexcloud/iexjs/blob/6a7768cd724ac7a114dd030deda53ece9de4d9d3/src/js/stocks/prices.js#L339

**Comment by nordicgit70** [comment]
I have the same problem with the npm package version 0.3.0.
However not with the version 0.3.1 downloaded from Github. 
Could you release the latest version?

```
await client.chart(instrument.ticker, { range: 'ytd', byDay: true });
```

**Comment by timkpaine** [comment]
@nordicgit70 as of 0.3.0 the arg was still called `timeframe` which was the original IEX API query param.

**Comment by carlwiedemann** [comment]
I suspect questions such as these may be solved by https://github.com/iexcloud/iexjs/issues/13, once better docs are available.

That said, it seems there could be improvements to the docs themselves wrt parameters. For example, the JSDoc block for the `chart` signature lists all *keys* for the `options` param as unique `@param`s themselves, when they should be listed using the "Parameters with properties" convention. See https://jsdoc.app/tags-param.html#parameters-with-properties

So, instead of

```js
/**
 * // ...
 * @param {string} symbol ticker to request
 * @param {string} timeframe Timeframe to request e.g. 1m
 * @param {string} date date, if requesting intraday
 * // etc...
 */
```

It should be something like

```js
/**
 * // ...
 * @param {string} symbol ticker to request
 * @param {object} options Chart options
 * @param {string} options.timeframe Timeframe to request e.g. 1m
 * @param {string} options.date date, if requesting intraday
 * // etc...
 */
```

Potentially this issue could be revised to instead focus on a general JSDoc formatting improvements, parameters with properties being a central goal.

**Comment by timkpaine** [comment]
@carlwiedemann yes this is in progress, e.g. https://github.com/iexcloud/iexjs/blob/main/src/js/stocks/news.js#L22

**Comment by carlwiedemann** [comment]
@timkpaine Thanks for the speedy reply, that's great to know its in-progress. 👍 

@yutingli119 @nordicgit70 Does the above discussion resolve your concerns? In the short term, consulting the source code function signatures is probably your best option rather than relying on the JSDoc `@param`s themselves. If so, then it seems that this issue could be closed.
